### ISSUE TITLE
Change airborne to apply only on hitting with tornado.

### ISSUE THREAD

**Issue by thicc-penguin** [klipsey/UnforgivenMod#2]
I love the mod, but I feel like Last Breath is very inconsistent because as long as an enemy is jumping/flying it counts as airborne, so you cannot really target with it because it will teleport you to an airborne enemy. 

I suggest allowing it to apply to every single target under a status effect caused by the first skill's tornado so that 1) last breath isn't useless against enemies immune to being airborne, 2) to allow more control over which targets are affected by last breath and 3) allow for every enemy affected to be hit by last breath properly (last breath currently only targets one enemy and does AOE damage around itself, tying it to the tornado would mean that it can now be made to affect every currently affected enemy)

Cheers!

**Comment by DamageMaximo** [comment]
I don't think limiting the use of a skill is gonna make the character much better

**Comment by thicc-penguin** [comment]
> I don't think limiting the use of a skill is gonna make the character much better

Obviously it would come with number changes. Plus I think the character would benefit from ulting actually important targets and not some random fucking wisp that just happened to be nearby.
